### ISSUE TITLE
Generated class has access public modifiers

### ISSUE THREAD

**Issue by arontsang** [ramoneeza/Rop.ProxyGenerator#1]
Means you can only apply on a class you want to make public.

```
[ProxyOf(nameof(IFoo), nameof(_foo))]
internal class Foo : IFoo
{
    private readonly IFoo _foo;
}

```

**Comment by ramoneeza** [comment]
Sorry, I don't undestand the question... can you provide an example?

**Comment by arontsang** [comment]
If I try to do the following:

```
[ProxyOf(nameof(IFoo), nameof(_foo))]
internal partial class Foo : IFoo
{
    private readonly IFoo _foo;
}
```

your library will generate

```
public partial class Foo
{
    public object Bar() => _foo.Bar();
}
```

The `public` will conflict with the `internal`.

**Comment by ramoneeza** [comment]
Ok... Ill try fix it as soon as possible

**Comment by ramoneeza** [comment]
Already Changed!!
Modifier checking add
